text1_data:
	 retlw 'P'
	 retlw 'i'
	 retlw 'e'
	 retlw 'r'
	 retlw 'w'
	 retlw 's'
	 retlw 'z'
	 retlw 'y'
	 retlw ' '
	 retlw 'n'
	 retlw 'a'
	 retlw 'p'
	 retlw 'i'
	 retlw 's'
	 retlw 0x00

text2_data:
	 retlw 'D'
	 retlw 'r'
	 retlw 'u'
	 retlw 'g'
	 retlw 'i'
	 retlw ' '
	 retlw 'n'
	 retlw 'a'
	 retlw 'p'
	 retlw 'i'
	 retlw 's'
	 retlw 0x00

text3_data:
	 retlw 'T'
	 retlw 'r'
	 retlw 'z'
	 retlw 'e'
	 retlw 'c'
	 retlw 'i'
	 retlw ' '
	 retlw 'n'
	 retlw 'a'
	 retlw 'p'
	 retlw 'i'
	 retlw 's'
	 retlw 0x00

text4_data:
	 retlw 'C'
	 retlw 'z'
	 retlw 'w'
	 retlw 'a'
	 retlw 'r'
	 retlw 't'
	 retlw 'y'
	 retlw ' '
	 retlw 'n'
	 retlw 'a'
	 retlw 'p'
	 retlw 'i'
	 retlw 's'
	 retlw 0x00

